// project/new/src/components/BO/API/ApiResponseViewer.tsx
import type { FormEvent } from "react";
import { useApiResponseViewer } from "../../hooks/useApiResponseViewer";
import "./ApiResponseViewer.css";

export function ApiResponseViewer() {
  const {
    resource,
    resourceId,
    paramsText,
    formattedResponse,
    isLoading,
    errorMessage,
    setResource,
    setResourceId,
    setParamsText,
    handleFetch,
  } = useApiResponseViewer();

  const onSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    await handleFetch();
  };

  return (
    <section className="api-viewer">
      <h2>API Response Viewer</h2>

      <form className="viewer-form" onSubmit={onSubmit}>
        <label>
          Resource
          <input
            value={resource}
            onChange={(event) => setResource(event.target.value)}
            type="text"
            placeholder="customers"
          />
        </label>

        <label>
          ID (optionnel)
          <input
            value={resourceId}
            onChange={(event) => setResourceId(event.target.value)}
            type="text"
            placeholder="42"
          />
        </label>

        <label>
          Query params (JSON)
          <textarea
            value={paramsText}
            onChange={(event) => setParamsText(event.target.value)}
            rows={5}
            placeholder='{"display":"[id,email]"}'
          />
        </label>

        <button type="submit" disabled={isLoading}>
          {isLoading ? "Chargement..." : "Charger la reponse API"}
        </button>
      </form>

      {errorMessage ? <p className="error">{errorMessage}</p> : null}
      {formattedResponse ? <pre className="result">{formattedResponse}</pre> : null}
    </section>
  );
}

// project/new/src/components/BO/API/ApiResponseViewer.vue
<template>
  <section class="api-viewer">
    <h2>API Response Viewer</h2>

    <form class="viewer-form" @submit.prevent="handleFetch">
      <label>
        Resource
        <input v-model="resource" type="text" placeholder="customers" />
      </label>

      <label>
        ID (optionnel)
        <input v-model="resourceId" type="text" placeholder="42" />
      </label>

      <label>
        Query params (JSON)
        <textarea
          v-model="paramsText"
          rows="5"
          placeholder='{"display":"[id,email]"}'
        ></textarea>
      </label>

      <button type="submit" :disabled="isLoading">
        {{ isLoading ? 'Chargement...' : 'Charger la reponse API' }}
      </button>
    </form>

    <p v-if="errorMessage" class="error">{{ errorMessage }}</p>

    <pre v-if="formattedResponse" class="result">{{ formattedResponse }}</pre>
  </section>
</template>

<script setup>
import { ref } from 'vue';
import { psGet } from '../../../utils/prestashop-api';

const resource = ref('customers');
const resourceId = ref('');
const paramsText = ref('{"display":"[id,email]"}');
const formattedResponse = ref('');
const isLoading = ref(false);
const errorMessage = ref('');

function parseParams() {
  if (!paramsText.value.trim()) {
    return {};
  }

  try {
    const parsed = JSON.parse(paramsText.value);
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    throw new Error('Le JSON des query params est invalide.');
  }
}

async function handleFetch() {
  errorMessage.value = '';
  formattedResponse.value = '';

  if (!resource.value.trim()) {
    errorMessage.value = 'La resource est obligatoire.';
    return;
  }

  isLoading.value = true;

  try {
    const queryParams = parseParams();
    const data = await psGet(resource.value.trim(), resourceId.value.trim(), queryParams);
    formattedResponse.value = JSON.stringify(data, null, 2);
  } catch (error) {
    errorMessage.value = error?.message || 'Erreur inconnue pendant l appel API.';
  } finally {
    isLoading.value = false;
  }
}
</script>

<style scoped>
.api-viewer {
  margin: 24px auto;
  width: min(920px, 96%);
  text-align: left;
}

.viewer-form {
  display: grid;
  gap: 12px;
}

label {
  display: grid;
  gap: 6px;
  font-weight: 600;
}

input,
textarea,
button {
  font: inherit;
  border: 1px solid #c8c8c8;
  border-radius: 8px;
  padding: 10px 12px;
}

button {
  cursor: pointer;
  background: #0b5fff;
  color: #fff;
  border-color: #0b5fff;
}

button:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.error {
  color: #be123c;
  font-weight: 600;
}

.result {
  background: #111827;
  color: #f9fafb;
  border-radius: 10px;
  padding: 14px;
  overflow: auto;
  max-height: 380px;
}
</style>
